# ----------------------------------------------------- 
# Autostart
# -----------------------------------------------------

# Setup XDG for screen sharing
exec-once = ~/.config/hypr/scripts/xdg.sh

# Start Polkit
# Test Polkit pkexec --user username alacritty
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Start ewww daemon
#exec-once = ags &

# Initialize waypaper
exec-once = hyprpaper

exec-once=/home/yurimds/.config/hypr/portalstart &

# Launch Waybar
exec-once = waybar

# Start autostart cleanup
exec-once = ~/.config/hypr/scripts/cleanup.sh
