# ----------------------------------------------------- 
# General window decoration
# ----------------------------------------------------- 

decoration {
  rounding = 10

  drop_shadow = yes
  shadow_range = 30
  shadow_render_power = 3
  col.shadow = rgba(1a1a1aee)

  active_opacity = 1.0
  inactive_opacity = 1.0

  blur {
     enabled = true
     size = 3
     passes = 1
     vibrancy = 0.1696
  }
}