# ----------------------------------------------------- 
# Layouts
# ----------------------------------------------------- 

dwindle {
  pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
  preserve_split = yes # you probably want this
  special_scale_factor = 0.8
}

master {
  new_on_top=1
  mfact = 0.5
}

gestures {
  #workspace_swipe = off
  workspace_swipe=1
  workspace_swipe_fingers=3
  workspace_swipe_distance=400
  workspace_swipe_invert=1
  workspace_swipe_min_speed_to_force=30
  workspace_swipe_cancel_ratio=0.5
  workspace_swipe_create_new=1 
  workspace_swipe_forever=1
}