# ----------------------------------------------------- 
# General window layout and colors
# ----------------------------------------------------- 
general {
  gaps_in = 5
  gaps_out = 10
  border_size = 2
  col.active_border = rgba(a9b665ff) # Bright Magenta
  col.inactive_border = rgba(ebdbb2ff) # White

  layout = dwindle

  allow_tearing = false
}

#Could help when scaling and not pixelating
xwayland {
    force_zero_scaling = true
}
