# Execute your favorite apps
exec-once = dbus-update-activation-environment --all
exec-once= /home/yurimds/.config/hypr/portalstart &
exec-once = waybar &
exec-once = hyprpaper &
exec-once = discord &
