#!/bin/sh

# settings for common commands
alias c="clear"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias bc="bc -ql"
alias mkd="mkdir -pv"
alias ls="eza --icons --group-directories-first"
alias locate="plocate"
alias tp="trash-put"
alias tpr="trash-restore"
alias cat='bat'
alias grep='grep --color=always'

alias fetch="fastfetch -l small"
alias vim="nvim"
alias dotfiles="nvim $HOME/dotfiles/"
alias neovim="nvim $HOME/Developer/neovim"

alias gcl="git clone"
alias gs="git status"
alias gadd="git add"
alias gc="git commit -m"
alias gpull="git pull"
alias gpush="git push"
alias gb="git branch"
